name: main
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']
  workflow_dispatch:

jobs:
  test_action:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM with caching
        uses: bahmutov/npm-install@v1.6.0

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run cypress:start
          wait-on: 'http://localhost:3000'

      - name: Run post tests
        run: npm run posttest

      - name: Report LCOV
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-files: ./coverage/lcov.info

      - name: Store coverage folder as artifact for deploy
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
